### ISSUE TITLE
Incomplete cookie scan results? Some comparisons.

### ISSUE THREAD

**Issue by ghost** [versluis/Cookies#1]
Thanks for creating this plugin. It's a missing piece for a lot of GDPR functionality available at the moment since most plugins charge for this functionality.

Show Me The Cookies reports 13 cookies and says this is a "list of all current cookies used on your site".

A partial scan (only 5 pages of the website) by Cookiebot reports 14 cookies.

Cookie Quick Manager plugin[1] for Firefox reports 17 cookies.

Is SMTC missing some cookies on the website? 

1: https://addons.mozilla.org/ga-IE/firefox/addon/cookie-quick-manager/

(Edit: changed numbers of cookies found by other plugins, as they were counting some set by the logged in admin user).

**Comment by versluis** [comment]
Hi! The plugin is very simple and lists everything thats exposed in the $_COOKIE variable provided by the browser. WordPress pulls this in, and I'm iterating through the values for sanitised display. There's a shortcode to display either all cookies, or remove the ones that WordPress uses internally. I've explained more in [this release article](https://wpguru.co.uk/2019/03/show-me-the-cookies-how-to-list-all-cookies-on-your-wordpress-site/).
Hope this helps!
